name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - main  # 设置你想要自动部署的分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # 设置你的Hexo项目所需的Node.js版本

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run:  hexo generate         # npm run build  # 或者是 hexo generate，取决于你的package.json中的脚本名称

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hexo生成的静态文件目录